services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"      
      - "15672:15672"    
    networks:
      - ms_network

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=certificates
    ports:
      - "5432:5432"      
    networks:
      - ms_network
    volumes:
    - ./postgres/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql  

  redis:
    image: redis
    ports:
      - "6379:6379"      
    networks:
      - ms_network

  worker:
    build:
      context: worker-certificate-generator
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - postgres
      - redis
    volumes:
      - pdf_storege:/app/pdf_files
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
      - DATABASE_NAME=mydatabase
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
    networks:
      - ms_network

  api:
    build: 
      context: api
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - postgres
      - redis
      - worker
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=certificates
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - ms_network
    ports:
      - "3000:3000"

volumes:
  pdf_storege:

networks:
  ms_network:
    driver: bridge
